name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-Github_Selfhosted_RUNNER-${{ github.run_id }}-${{ github.run_attempt }} -with-buildspec
    steps:
      - run: echo "Hello World! 2"
