name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-UploadtoS3_GithubRunner-${{ github.run_id }}-${{ github.run_attempt }} 
    steps:
      - run: echo "Running action workflow from github"
